### ISSUE TITLE
与自动翻页插件共用不适配

### ISSUE THREAD

**Issue by karlmorghulis** [MerielVaren/remove-link-redirects#1]
与以下脚本自动翻页插件一起使用的话,bing搜索加载到第二页,会自动弹回网页顶部

[### 相关的连接](https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5)

**Comment by MerielVaren** [comment]
@karlmorghulis 试一下2.1.4版本还有这个bug吗，我这边自测了一下没有了
