### ISSUE TITLE
新版本后，youtube无限重载

### ISSUE THREAD

**Issue by wangxiangg1** [MerielVaren/remove-link-redirects#2]
### BUG 描述

> 请对这个 BUG 进行描述

### 相关的连接
https://www.youtube.com/@areiacreations/search
> 请填写有重定向链接的网页地址，方便我定位排查
>https://www.youtube.com/@areiacreations/search
> 个人精力有限，我不太可能会在网站中一个一个的去找，感谢你的理解
在下面搜索一个人物比如BLAKPINK 然后网站就会不断的打断重载，想到刚才升级了你这脚本，我关闭脚本就正常了。之前没有相关问题，对了，包括观看合集也会出问题

**Comment by MerielVaren** [comment]
试一下2.1.4版本还会出现这个bug吗

**Comment by MerielVaren** [comment]
@wangxiangg1
