### ISSUE TITLE
百度百家号重定向失败变成直接搜索

### ISSUE THREAD

**Issue by dunkeng** [MerielVaren/remove-link-redirects#4]
### BUG 描述

比如附带链接的搜索，打开最上边会有几个“最新相关信息”，点里面任何一项，正常会到百家号的网页，可以看到内容，现在变成了直接百度搜索关键字

### 相关的链接

https://www.baidu.com/s?wd=%E5%B1%B1%E4%B8%9C%E4%B8%80%E7%94%B7%E5%AD%90%E6%8B%92%E6%9C%8D%E5%85%B5%E5%BD%B9%E8%A2%AB%E6%83%A9%E6%88%92&ie=utf-8

正常情况：
https://baijiahao.baidu.com/s?id=1804358398574514361

当前问题：
https://www.baidu.com/s?rtt=1&wd=%E5%B1%B1%E4%B8%9C%E4%B8%80%E7%94%B7%E5%AD%90%E6%8B%92%E6%9C%8D%E5%85%B5%E5%BD%B9%E8%A2%AB%E6%83%A9%E6%88%92

**Comment by MerielVaren** [comment]
感谢你的反馈，现在已经修复了这个bug。

**Comment by dunkeng** [comment]
又有新问题了，
相关链接：
https://www.baidu.com/s?wd=%E8%BF%90%E5%8A%A8%E5%91%98%E8%AF%BB%E8%87%AA%E5%B7%B1%E5%90%8D%E5%AD%97%E9%80%90%E6%B8%90%E6%9A%B4%E8%BA%81&ie=utf-8

正常情况：
https://mbd.baidu.com/newspage/data/videolanding?nid=sv_1337949688501052725

当前：
https://www.baidu.com/undefined

**Comment by MerielVaren** [comment]
> 又有新问题了， 相关链接： https://www.baidu.com/s?wd=%E8%BF%90%E5%8A%A8%E5%91%98%E8%AF%BB%E8%87%AA%E5%B7%B1%E5%90%8D%E5%AD%97%E9%80%90%E6%B8%90%E6%9A%B4%E8%BA%81&ie=utf-8
> 
> 正常情况： https://mbd.baidu.com/newspage/data/videolanding?nid=sv_1337949688501052725
> 
> 当前： https://www.baidu.com/undefined

这个情况在哪里啊，我把前三页都点了也没发现这个问题
