### ISSUE TITLE
请求适配腾讯文档跳转

### ISSUE THREAD

**Issue by chenbihao** [MerielVaren/remove-link-redirects#5]
例如这个文档：https://docs.qq.com/sheet/DQ1lqSWFSRGNRa05i?tab=BB08J2

点击链接格子时会打开新标签页：

https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1QU4y1R7hg%2F&pid=300000000$CYjIaRDcQkNb&cid=144115212913152770

**Comment by MerielVaren** [comment]
> 例如这个文档：https://docs.qq.com/sheet/DQ1lqSWFSRGNRa05i?tab=BB08J2
> 
> 点击链接格子时会打开新标签页：
> 
> https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1QU4y1R7hg%2F&pid=300000000$CYjIaRDcQkNb&cid=144115212913152770

已适配

**Comment by MerielVaren** [comment]
有bug，已修复，本issue关闭
