### ISSUE TITLE
百度问题反馈

### ISSUE THREAD

**Issue by ahdung** [MerielVaren/remove-link-redirects#6]
https://www.baidu.com/link?url=lxPTqPTGGBnBfdsWqp_sYqa0KjUlpIhONazR5oc30i1ywYrMnW1q6YG0Q7sQTnE9waYcbgVfVtUOVchhwNwsttGH7k9GD2_ggrIGQtxm4Kgx7LCBZEdd0xdqWZTzPy7E&wd=&eqid=99140ebf017663760000000666b2e74b

会搞成：https://www.baidu.com/undefined
![image](https://github.com/user-attachments/assets/6fd91999-f26d-4371-9382-2c6b7faa22f4)

实际URL：https://mbd.baidu.com/newspage/data/videolanding?nid=sv_287601591259243815&sourceFrom=qmj
![微信截图_20240807112235](https://github.com/user-attachments/assets/9cf145b6-7a6c-4f8e-8a24-684c9feb259a)

**Comment by MerielVaren** [comment]
2.5.6版本解决了这个issue
此外还要感谢您，您的这个issue涉及到了js的event loop以及promise的相关trick，让后端程序员的我半吊子的js水平又进了一步，对js的理解又加深了
