### ISSUE TITLE
谷歌搜索问题

### ISSUE THREAD

**Issue by aoguai** [MerielVaren/remove-link-redirects#7]
最新版本
搜索页面正常，任意链接点击后直接 变404
关闭插件后恢复正常
![3CF223067E40429F6C6E561797B67F7E](https://github.com/user-attachments/assets/f2cd1eae-7bc1-4d15-9b6a-92470573db6d)
![668D8D8A0B0239836C8BF82233C5173A](https://github.com/user-attachments/assets/038633f3-12cd-449c-9969-f26f9354cc98)

**Comment by MerielVaren** [comment]
前天做谷歌相关修复的时候提交了一个漏洞版本，现在应该已经修复了，还有这个问题吗

**Comment by aoguai** [comment]
2.6.3版本后正常
