### ISSUE TITLE
百度问题

### ISSUE THREAD

**Issue by ahdung** [MerielVaren/remove-link-redirects#8]
# 不使用该脚本时：
链接是：https://www.baidu.com/link?url=omprRq0DCpJ2D_oo4EpKiV6lIprBjR53_X8btwdNaddmChOmOXjD2-p9IzKuR00mbfFOjsSszWpEO82mJUYX9a
![微信截图_20240827113406](https://github.com/user-attachments/assets/508fa522-c288-408b-8c1b-bb93336882f9)

点进去后的链接是：https://zhidao.baidu.com/question/182380422.html
![微信截图_20240827113132](https://github.com/user-attachments/assets/b88c9693-22a4-48c7-8d31-0097b227d76e)

# 开启本脚本后：
这一挂链接统统变成：https://zhidao.baidu.com/question/659794839024687005.html
![微信截图_20240827113310](https://github.com/user-attachments/assets/91b1763e-dee6-4dcd-bcd6-9dc949fc7497)

**Comment by MerielVaren** [comment]
@ahdung 2.6.7版本已修复这个问题，可以看一下还有没有出现

**Comment by ahdung** [comment]
感谢作者，我一直留在2.6.6，没留意2.6.7已经解决了，抱歉。
